// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lsprpc/channel.proto

package lsprpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpenChannelRequest struct {
	Pubkey               string   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	AmountMsat           uint64   `protobuf:"varint,3,opt,name=amount_msat,json=amountMsat,proto3" json:"amount_msat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenChannelRequest) Reset()         { *m = OpenChannelRequest{} }
func (m *OpenChannelRequest) String() string { return proto.CompactTextString(m) }
func (*OpenChannelRequest) ProtoMessage()    {}
func (*OpenChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ff1f930398b2a84, []int{0}
}

func (m *OpenChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenChannelRequest.Unmarshal(m, b)
}
func (m *OpenChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenChannelRequest.Marshal(b, m, deterministic)
}
func (m *OpenChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenChannelRequest.Merge(m, src)
}
func (m *OpenChannelRequest) XXX_Size() int {
	return xxx_messageInfo_OpenChannelRequest.Size(m)
}
func (m *OpenChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenChannelRequest proto.InternalMessageInfo

func (m *OpenChannelRequest) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *OpenChannelRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OpenChannelRequest) GetAmountMsat() uint64 {
	if m != nil {
		return m.AmountMsat
	}
	return 0
}

type OpenChannelResponse struct {
	PendingChanId        []byte   `protobuf:"bytes,1,opt,name=pending_chan_id,json=pendingChanId,proto3" json:"pending_chan_id,omitempty"`
	Scid                 uint64   `protobuf:"varint,2,opt,name=scid,proto3" json:"scid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenChannelResponse) Reset()         { *m = OpenChannelResponse{} }
func (m *OpenChannelResponse) String() string { return proto.CompactTextString(m) }
func (*OpenChannelResponse) ProtoMessage()    {}
func (*OpenChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ff1f930398b2a84, []int{1}
}

func (m *OpenChannelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenChannelResponse.Unmarshal(m, b)
}
func (m *OpenChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenChannelResponse.Marshal(b, m, deterministic)
}
func (m *OpenChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenChannelResponse.Merge(m, src)
}
func (m *OpenChannelResponse) XXX_Size() int {
	return xxx_messageInfo_OpenChannelResponse.Size(m)
}
func (m *OpenChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenChannelResponse proto.InternalMessageInfo

func (m *OpenChannelResponse) GetPendingChanId() []byte {
	if m != nil {
		return m.PendingChanId
	}
	return nil
}

func (m *OpenChannelResponse) GetScid() uint64 {
	if m != nil {
		return m.Scid
	}
	return 0
}

func init() {
	proto.RegisterType((*OpenChannelRequest)(nil), "channel.OpenChannelRequest")
	proto.RegisterType((*OpenChannelResponse)(nil), "channel.OpenChannelResponse")
}

func init() { proto.RegisterFile("lsprpc/channel.proto", fileDescriptor_2ff1f930398b2a84) }

var fileDescriptor_2ff1f930398b2a84 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0x87, 0xa9, 0x2e, 0x2b, 0xce, 0xfa, 0x07, 0x46, 0x91, 0xa2, 0x82, 0xeb, 0x0a, 0xb2, 0x17,
	0x5b, 0xd0, 0x37, 0xd0, 0x8b, 0x1e, 0x44, 0xac, 0xb7, 0xbd, 0x94, 0x34, 0x1d, 0xba, 0xc1, 0x36,
	0x89, 0x9d, 0x54, 0xf0, 0xed, 0xa5, 0x49, 0x04, 0xc5, 0xbd, 0xcd, 0xf7, 0x1b, 0x92, 0x6f, 0x66,
	0xe0, 0xb8, 0x65, 0xdb, 0x5b, 0x99, 0xcb, 0xb5, 0xd0, 0x9a, 0xda, 0xcc, 0xf6, 0xc6, 0x19, 0xdc,
	0x89, 0xb8, 0x20, 0xc0, 0x17, 0x4b, 0xfa, 0x21, 0x60, 0x41, 0x1f, 0x03, 0xb1, 0xc3, 0x13, 0x98,
	0xda, 0xa1, 0x7a, 0xa7, 0xaf, 0x34, 0x99, 0x27, 0xcb, 0xdd, 0x22, 0xd2, 0x98, 0x8b, 0xce, 0x0c,
	0xda, 0xa5, 0x5b, 0xf3, 0x64, 0x39, 0x29, 0x22, 0xe1, 0x05, 0xcc, 0x42, 0x55, 0x76, 0x2c, 0x5c,
	0xba, 0xed, 0x9b, 0x10, 0xa2, 0x67, 0x16, 0x6e, 0xf1, 0x0a, 0x47, 0x7f, 0x34, 0x6c, 0x8d, 0x66,
	0xc2, 0x6b, 0x38, 0xb4, 0xa4, 0x6b, 0xa5, 0x9b, 0x72, 0x1c, 0xa8, 0x54, 0xb5, 0x17, 0xee, 0x15,
	0xfb, 0x31, 0x1e, 0x1f, 0x3c, 0xd5, 0x88, 0x30, 0x61, 0xa9, 0xea, 0x68, 0xf5, 0xf5, 0xed, 0x0a,
	0x0e, 0xe2, 0x77, 0x6f, 0xd4, 0x7f, 0x2a, 0x49, 0xf8, 0x08, 0xb3, 0x5f, 0x12, 0x3c, 0xcb, 0x7e,
	0x76, 0xfe, 0xbf, 0xe1, 0xe9, 0xf9, 0xe6, 0x66, 0x98, 0xeb, 0xfe, 0x6a, 0x75, 0xd9, 0x28, 0xb7,
	0x1e, 0xaa, 0x4c, 0x9a, 0x2e, 0x67, 0xe1, 0x54, 0x67, 0x9c, 0xc9, 0x1b, 0x73, 0xd3, 0xb2, 0xcd,
	0xc3, 0x45, 0xab, 0xa9, 0x3f, 0xe5, 0xdd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x54, 0xc0,
	0x17, 0x62, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChannelServiceClient is the client API for ChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChannelServiceClient interface {
	OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error)
}

type channelServiceClient struct {
	cc *grpc.ClientConn
}

func NewChannelServiceClient(cc *grpc.ClientConn) ChannelServiceClient {
	return &channelServiceClient{cc}
}

func (c *channelServiceClient) OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error) {
	out := new(OpenChannelResponse)
	err := c.cc.Invoke(ctx, "/channel.ChannelService/OpenChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServiceServer is the server API for ChannelService service.
type ChannelServiceServer interface {
	OpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error)
}

// UnimplementedChannelServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChannelServiceServer struct {
}

func (*UnimplementedChannelServiceServer) OpenChannel(ctx context.Context, req *OpenChannelRequest) (*OpenChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChannel not implemented")
}

func RegisterChannelServiceServer(s *grpc.Server, srv ChannelServiceServer) {
	s.RegisterService(&_ChannelService_serviceDesc, srv)
}

func _ChannelService_OpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).OpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/channel.ChannelService/OpenChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).OpenChannel(ctx, req.(*OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChannelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "channel.ChannelService",
	HandlerType: (*ChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenChannel",
			Handler:    _ChannelService_OpenChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lsprpc/channel.proto",
}
