// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lsprpc/invoice.proto

package lsprpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateInvoiceRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentRequest       string   `protobuf:"bytes,3,opt,name=payment_request,json=paymentRequest,proto3" json:"payment_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInvoiceRequest) Reset()         { *m = UpdateInvoiceRequest{} }
func (m *UpdateInvoiceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInvoiceRequest) ProtoMessage()    {}
func (*UpdateInvoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fef7841c2201b9b, []int{0}
}

func (m *UpdateInvoiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInvoiceRequest.Unmarshal(m, b)
}
func (m *UpdateInvoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInvoiceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInvoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInvoiceRequest.Merge(m, src)
}
func (m *UpdateInvoiceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInvoiceRequest.Size(m)
}
func (m *UpdateInvoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInvoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInvoiceRequest proto.InternalMessageInfo

func (m *UpdateInvoiceRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateInvoiceRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateInvoiceRequest) GetPaymentRequest() string {
	if m != nil {
		return m.PaymentRequest
	}
	return ""
}

type UpdateInvoiceResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentRequest       string   `protobuf:"bytes,3,opt,name=payment_request,json=paymentRequest,proto3" json:"payment_request,omitempty"`
	IsSettled            bool     `protobuf:"varint,4,opt,name=is_settled,json=isSettled,proto3" json:"is_settled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInvoiceResponse) Reset()         { *m = UpdateInvoiceResponse{} }
func (m *UpdateInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateInvoiceResponse) ProtoMessage()    {}
func (*UpdateInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fef7841c2201b9b, []int{1}
}

func (m *UpdateInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInvoiceResponse.Unmarshal(m, b)
}
func (m *UpdateInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInvoiceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInvoiceResponse.Merge(m, src)
}
func (m *UpdateInvoiceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateInvoiceResponse.Size(m)
}
func (m *UpdateInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInvoiceResponse proto.InternalMessageInfo

func (m *UpdateInvoiceResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateInvoiceResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateInvoiceResponse) GetPaymentRequest() string {
	if m != nil {
		return m.PaymentRequest
	}
	return ""
}

func (m *UpdateInvoiceResponse) GetIsSettled() bool {
	if m != nil {
		return m.IsSettled
	}
	return false
}

func init() {
	proto.RegisterType((*UpdateInvoiceRequest)(nil), "invoice.UpdateInvoiceRequest")
	proto.RegisterType((*UpdateInvoiceResponse)(nil), "invoice.UpdateInvoiceResponse")
}

func init() { proto.RegisterFile("lsprpc/invoice.proto", fileDescriptor_5fef7841c2201b9b) }

var fileDescriptor_5fef7841c2201b9b = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0x56, 0x5a, 0x3b, 0x60, 0x84, 0xa5, 0x62, 0x10, 0x2a, 0xb1, 0x1e, 0xcc, 0xc5,
	0x04, 0xf4, 0x1f, 0x78, 0xeb, 0xc5, 0x43, 0x8a, 0x17, 0x2f, 0x31, 0xcd, 0x0e, 0xed, 0x40, 0x92,
	0x5d, 0x77, 0x26, 0x05, 0xff, 0x81, 0x3f, 0x5b, 0xec, 0xc6, 0x83, 0xa2, 0x37, 0x8f, 0xef, 0x5b,
	0x76, 0xdf, 0xdb, 0xf7, 0x60, 0xde, 0xb0, 0xf3, 0xae, 0xce, 0xa9, 0xdb, 0x5b, 0xaa, 0x31, 0x73,
	0xde, 0x8a, 0xd5, 0xd3, 0x41, 0x2e, 0x77, 0x30, 0x7f, 0x72, 0xa6, 0x12, 0x5c, 0x05, 0x50, 0xe0,
	0x6b, 0x8f, 0x2c, 0x3a, 0x82, 0x11, 0x99, 0x58, 0x25, 0x2a, 0x1d, 0x17, 0x23, 0x32, 0xfa, 0x1c,
	0xa6, 0x3d, 0xa3, 0x2f, 0xc9, 0xc4, 0xa3, 0x03, 0x9c, 0x7c, 0xca, 0x95, 0xd1, 0x37, 0x70, 0xea,
	0xaa, 0xb7, 0x16, 0x3b, 0x29, 0x7d, 0xb8, 0x1b, 0x8f, 0x13, 0x95, 0xce, 0x8a, 0x68, 0xc0, 0xc3,
	0x8b, 0xcb, 0x77, 0x05, 0x67, 0x3f, 0xac, 0xd8, 0xd9, 0x8e, 0xf1, 0xff, 0xbd, 0xf4, 0x02, 0x80,
	0xb8, 0x64, 0x14, 0x69, 0xd0, 0xc4, 0x47, 0x89, 0x4a, 0x8f, 0x8b, 0x19, 0xf1, 0x3a, 0x80, 0xbb,
	0x17, 0x88, 0x86, 0x0c, 0x6b, 0xf4, 0x7b, 0xaa, 0x51, 0x3f, 0xc2, 0xc9, 0xb7, 0x6c, 0x7a, 0x91,
	0x7d, 0x15, 0xf6, 0x5b, 0x3d, 0x17, 0x97, 0x7f, 0x1d, 0x87, 0x2f, 0x3d, 0x5c, 0x3f, 0x5f, 0x6d,
	0x49, 0x76, 0xfd, 0x26, 0xab, 0x6d, 0x9b, 0x73, 0x25, 0xd4, 0x5a, 0xb1, 0xf9, 0xd6, 0xde, 0x36,
	0xec, 0xf2, 0x30, 0xc9, 0x66, 0x72, 0xd8, 0xe2, 0xfe, 0x23, 0x00, 0x00, 0xff, 0xff, 0x65, 0xdb,
	0xbc, 0xe6, 0xa3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InvoiceServiceClient is the client API for InvoiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvoiceServiceClient interface {
	UpdateInvoice(ctx context.Context, in *UpdateInvoiceRequest, opts ...grpc.CallOption) (*UpdateInvoiceResponse, error)
}

type invoiceServiceClient struct {
	cc *grpc.ClientConn
}

func NewInvoiceServiceClient(cc *grpc.ClientConn) InvoiceServiceClient {
	return &invoiceServiceClient{cc}
}

func (c *invoiceServiceClient) UpdateInvoice(ctx context.Context, in *UpdateInvoiceRequest, opts ...grpc.CallOption) (*UpdateInvoiceResponse, error) {
	out := new(UpdateInvoiceResponse)
	err := c.cc.Invoke(ctx, "/invoice.InvoiceService/UpdateInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoiceServiceServer is the server API for InvoiceService service.
type InvoiceServiceServer interface {
	UpdateInvoice(context.Context, *UpdateInvoiceRequest) (*UpdateInvoiceResponse, error)
}

// UnimplementedInvoiceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInvoiceServiceServer struct {
}

func (*UnimplementedInvoiceServiceServer) UpdateInvoice(ctx context.Context, req *UpdateInvoiceRequest) (*UpdateInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInvoice not implemented")
}

func RegisterInvoiceServiceServer(s *grpc.Server, srv InvoiceServiceServer) {
	s.RegisterService(&_InvoiceService_serviceDesc, srv)
}

func _InvoiceService_UpdateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).UpdateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.InvoiceService/UpdateInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).UpdateInvoice(ctx, req.(*UpdateInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InvoiceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "invoice.InvoiceService",
	HandlerType: (*InvoiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateInvoice",
			Handler:    _InvoiceService_UpdateInvoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lsprpc/invoice.proto",
}
